name: Run Hello-world from py Script
on: push

jobs:
  Hello:
    runs-on: ubuntu-latest

    steps:
    - name: Clone Repo
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
        with:
          python-version: '3.13' 
        
    - name: List files
      run: ls -la

    - name: Run a py Script
      run: python hello.py
